### ISSUE TITLE
Incomplete generated directory structure

### ISSUE THREAD

**Issue by Hrshl7** [cebtenzzre/tumblr-utils#29] opened 2024-09-06 18:32 UTC
I downloaded tumblr-backup today (6th september 2024) and proceeded to follow the readme. However, while I am able to proceed with the command, the resulting folder is missing most of its content.
Only the folders `posts`, `media` and `theme` are created, and both `media` and `theme` are empty. There is also a `.first_run_options` file within the `blog-name` folder.

I also get a lot of `Caught exception while saving post _number_string_:` similar to issue #27 but without mention of any `Unable to download video in post #170435533203`.

I uninstalled and reinstalled tumblr-backup several times and updated pip and urllib3 without improvement.

As a last detail, I used to rely on the DEFAULT_BLOGS listed in settings.py to run the backup of all my blogs (I have a lot), however I cannot do that anymore. Listing several blogs in the command each time is not only bothersome but it also only backups the first listed and then stops, disregarding the others.

**Comment by cebtenzzre** [comment] 2024-12-03 21:39
Duplicate of #27

**Closed by cebtenzzre** 2024-12-03 21:39 UTC
