### ISSUE TITLE
Exceptions while saving posts

### ISSUE THREAD

**Issue by EternityEngine** [cebtenzzre/tumblr-utils#30] opened 2024-10-18 07:00 UTC
Download date: October 17, 2024 (through pip)
Command: `tumblr-backup -n 9 -s 2 -j eternityengine`
Relevant console output/backtrace: [log.txt](https://github.com/user-attachments/files/17429636/log.txt)
Links to posts causing exceptions: [1](https://eternityengine.tumblr.com/post/763929349796806656), [2](https://eternityengine.tumblr.com/post/763926216637022208), [3](https://eternityengine.tumblr.com/post/763925014077751296), [4](https://eternityengine.tumblr.com/post/763627894570450944), [5](https://eternityengine.tumblr.com/post/763082883831398400), [6](https://eternityengine.tumblr.com/post/763166612265254912)
Python version: 3.12.0 (32-bit)

The posts are (perhaps obviously) not saved afterwards.

**Comment by cebtenzzre** [comment] 2024-12-04 18:58
Duplicate of #27, which is now fixed as of 1.0.4.

**Closed by cebtenzzre** 2024-12-04 18:58 UTC
